[package]
name = "datrie"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
range-map = "0.2"

[dev-dependencies]
cdatrie = { path = "../cdatrie" }
