use ::libc;
pub type thchar_t = libc::c_uchar;
pub const _th_IStis: C2RustUnnamed = 1;
pub const _th_ISpunct: C2RustUnnamed = 1024;
pub const _th_ISdigit: C2RustUnnamed = 512;
pub const _th_ISdiac: C2RustUnnamed = 256;
pub const _th_IStone: C2RustUnnamed = 128;
pub const _th_VCflvowel: C2RustUnnamed = 16;
pub const _th_VCldvowel: C2RustUnnamed = 48;
pub const _th_VCblvowel: C2RustUnnamed = 112;
pub const _th_VCupvowel: C2RustUnnamed = 80;
pub const _th_IScons: C2RustUnnamed = 2;
pub const _th_CCovershoot: C2RustUnnamed = 6;
pub const _th_CCundersplit: C2RustUnnamed = 14;
pub const _th_CCundershoot: C2RustUnnamed = 10;
pub const _th_ISvowel: C2RustUnnamed = 16;
pub const _th_CCtailless: C2RustUnnamed = 2;
pub const _th_CClassMsk: C2RustUnnamed = 14;
pub const _th_VClassMsk: C2RustUnnamed = 112;
pub type C2RustUnnamed = libc::c_uint;
pub const _none: libc::c_int = 0 as libc::c_int;
pub const _cntrl: libc::c_int = _th_IStis as libc::c_int;
pub const _space: libc::c_int = _th_IStis as libc::c_int;
pub const _edigit: libc::c_int = _th_IStis as libc::c_int | _th_ISdigit as libc::c_int;
pub const _elower: libc::c_int = _th_IStis as libc::c_int;
pub const _eupper: libc::c_int = _th_IStis as libc::c_int;
pub const _epunct: libc::c_int = _th_IStis as libc::c_int | _th_ISpunct as libc::c_int;
pub const _tdigit: libc::c_int = _th_IStis as libc::c_int | _th_ISdigit as libc::c_int;
pub const _tcons: libc::c_int = _th_IStis as libc::c_int | _th_IScons as libc::c_int;
pub const _tflvowel: libc::c_int = _th_IStis as libc::c_int | _th_VCflvowel as libc::c_int;
pub const _tldvowel: libc::c_int = _th_IStis as libc::c_int | _th_VCldvowel as libc::c_int;
pub const _tupvowel: libc::c_int = _th_IStis as libc::c_int | _th_VCupvowel as libc::c_int;
pub const _tblvowel: libc::c_int = _th_IStis as libc::c_int | _th_VCblvowel as libc::c_int;
pub const _ttone: libc::c_int = _th_IStis as libc::c_int | _th_IStone as libc::c_int;
pub const _tdiac: libc::c_int = _th_IStis as libc::c_int | _th_ISdiac as libc::c_int;
pub const _tpunct: libc::c_int = _th_IStis as libc::c_int | _th_ISpunct as libc::c_int;
#[no_mangle]
pub static mut _th_ctype_tbl: [libc::c_ushort; 256] = [
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _space as libc::c_ushort,
    _space as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _space as libc::c_ushort,
    _space as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _space as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _edigit as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _eupper as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _elower as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _epunct as libc::c_ushort,
    _cntrl as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    (_tcons | _th_CCundersplit as libc::c_int) as libc::c_ushort,
    (_tcons | _th_CCundershoot as libc::c_int) as libc::c_ushort,
    (_tcons | _th_CCundershoot as libc::c_int) as libc::c_ushort,
    (_tcons | _th_CCundersplit as libc::c_int) as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    (_tcons | _th_CCovershoot as libc::c_int) as libc::c_ushort,
    _tcons as libc::c_ushort,
    (_tcons | _th_CCovershoot as libc::c_int) as libc::c_ushort,
    _tcons as libc::c_ushort,
    (_tcons | _th_CCovershoot as libc::c_int) as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tflvowel as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tflvowel as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    (_tcons | _th_CCovershoot as libc::c_int) as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tcons as libc::c_ushort,
    _tpunct as libc::c_ushort,
    _tflvowel as libc::c_ushort,
    _tupvowel as libc::c_ushort,
    _tflvowel as libc::c_ushort,
    _tflvowel as libc::c_ushort,
    _tupvowel as libc::c_ushort,
    _tupvowel as libc::c_ushort,
    _tupvowel as libc::c_ushort,
    _tupvowel as libc::c_ushort,
    _tblvowel as libc::c_ushort,
    _tblvowel as libc::c_ushort,
    _tdiac as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _tpunct as libc::c_ushort,
    _tldvowel as libc::c_ushort,
    _tldvowel as libc::c_ushort,
    _tldvowel as libc::c_ushort,
    _tldvowel as libc::c_ushort,
    _tldvowel as libc::c_ushort,
    _tflvowel as libc::c_ushort,
    _tpunct as libc::c_ushort,
    _tdiac as libc::c_ushort,
    _ttone as libc::c_ushort,
    _ttone as libc::c_ushort,
    _ttone as libc::c_ushort,
    _ttone as libc::c_ushort,
    _tdiac as libc::c_ushort,
    _tdiac as libc::c_ushort,
    _tdiac as libc::c_ushort,
    _tpunct as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tdigit as libc::c_ushort,
    _tpunct as libc::c_ushort,
    _tpunct as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
    _none as libc::c_ushort,
];
#[no_mangle]
pub static mut _th_chlevel_tbl: [libc::c_int; 256] = [
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    1 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    1 as libc::c_int,
    1 as libc::c_int,
    1 as libc::c_int,
    1 as libc::c_int,
    -(1 as libc::c_int),
    -(1 as libc::c_int),
    -(1 as libc::c_int),
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    3 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    2 as libc::c_int,
    3 as libc::c_int,
    1 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
    0 as libc::c_int,
];
#[no_mangle]
pub unsafe extern "C" fn th_istis(mut c: thchar_t) -> libc::c_int {
    return _th_ctype_tbl[c as usize] as libc::c_int & _th_IStis as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isthai(mut c: thchar_t) -> libc::c_int {
    return (th_istis(c) != 0 && c as libc::c_int & 0x80 as libc::c_int != 0) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_iseng(mut c: thchar_t) -> libc::c_int {
    return (c as libc::c_int & 0x80 as libc::c_int == 0) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isthcons(mut c: thchar_t) -> libc::c_int {
    return _th_ctype_tbl[c as usize] as libc::c_int & _th_IScons as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isthvowel(mut c: thchar_t) -> libc::c_int {
    return _th_ctype_tbl[c as usize] as libc::c_int & _th_ISvowel as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isthtone(mut c: thchar_t) -> libc::c_int {
    return _th_ctype_tbl[c as usize] as libc::c_int & _th_IStone as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isthdiac(mut c: thchar_t) -> libc::c_int {
    return _th_ctype_tbl[c as usize] as libc::c_int & _th_ISdiac as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isthdigit(mut c: thchar_t) -> libc::c_int {
    return _th_ctype_tbl[c as usize] as libc::c_int & _th_ISdigit as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isthpunct(mut c: thchar_t) -> libc::c_int {
    return _th_ctype_tbl[c as usize] as libc::c_int & _th_ISpunct as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_istaillesscons(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_CClassMsk as libc::c_int
        == _th_CCtailless as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isovershootcons(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_CClassMsk as libc::c_int
        == _th_CCovershoot as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isundershootcons(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_CClassMsk as libc::c_int
        == _th_CCundershoot as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isundersplitcons(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_CClassMsk as libc::c_int
        == _th_CCundersplit as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isldvowel(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_VClassMsk as libc::c_int
        == _th_VCldvowel as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isflvowel(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_VClassMsk as libc::c_int
        == _th_VCflvowel as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isupvowel(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_VClassMsk as libc::c_int
        == _th_VCupvowel as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_isblvowel(mut c: thchar_t) -> libc::c_int {
    return (_th_ctype_tbl[c as usize] as libc::c_int & _th_VClassMsk as libc::c_int
        == _th_VCblvowel as libc::c_int) as libc::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn th_chlevel(mut c: thchar_t) -> libc::c_int {
    return _th_chlevel_tbl[c as usize];
}
#[no_mangle]
pub unsafe extern "C" fn th_iscombchar(mut c: thchar_t) -> libc::c_int {
    return (_th_chlevel_tbl[c as usize] != 0 as libc::c_int) as libc::c_int;
}
