[package]
name = "cdatrie"
version = "0.1.0"
edition = "2021"
license = "MIT"
links = "datrie"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.63.0"
